import type {Metadata} from "next";
import {DM_Sans} from "next/font/google";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "next-themes";
import {twMerge} from "tailwind-merge";
import AppStateProvider from "@/lib/providers/state-provider";
import {SupabaseUserProvider} from "@/lib/providers/supabase-user-provider";
import {Toaster} from "@/components/ui/toaster";

// import db from "@/lib/supabase/db";
// if (db) {
//     console.log('Database loaded');
// }

const inter = DM_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Cypress",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            suppressHydrationWarning={true}
            lang="en"
        >
        <body
            suppressHydrationWarning={true}
            className={twMerge("bg-background", inter.className)}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
        >
            <AppStateProvider>
                <SupabaseUserProvider>
                    {children}
                    <Toaster/>
                </SupabaseUserProvider>
            </AppStateProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
